#启动端口
server:
  port: 9083

spring:
  profiles:
    active: dev
  application:
    name: xweb-amqp
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: fengye
    password: fengye
    virtualHost: 5672
#  profiles:
#    active: @project.environment@

## Actuator监控端口
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env,bus-refresh
  endpoint:
    health:
      show-details: always
    info:
      enabled: true

