#启动端口
server:
  port: 9084

## Actuator监控端口
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env,bus-refresh
  endpoint:
    health:
      show-details: always
    info:
      enabled: true

