## 生产环境 数据源信息
base:
  datasource:
    url: pay-xiaopay.rwlb.rds.aliyuncs.com
    username: fengye
    password: Pay2020fy
    driver: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource