## 测试环境 数据源信息
base:
  datasource:
    url: rm-bp1s2c6js6podc1baro.mysql.rds.aliyuncs.com
    username: testuser
    password: Anzhipay2020
    driver: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource